FROM continuumio/miniconda3

# Set up environment
RUN conda create -n conda_env1 python=3.8

# Activate environment
RUN echo "source activate conda_env1" > ~/.bashrc
ENV PATH /opt/conda/envs/conda_env1/bin:$PATH

# Copy and install script dependencies
COPY create_SAP_info.py /app/
WORKDIR /app
RUN pip install -r requirements.txt

CMD ["python", "create_SAP_info.py"]